"use strict";
const $ = id => document.getElementById(id);
let controller = null;
let generation = 0;
let toolResult = null; // Page memory only; never regenerated by a narration model.
const text = value => value === null ? "NULL (no value)" : typeof value === "object" ? JSON.stringify(value) : String(value);
function list(id, values) {
  $(id).replaceChildren(...(values || []).map(value => {
    const li = document.createElement("li"); li.textContent = text(value); return li;
  }));
}
function render(payload) {
  toolResult = payload;
  $("result").hidden = false;
  $("status").textContent = ({answered:"Query complete",failed:"Execution failed",clarify:"Clarification needed",semantic_gap:"Missing business definition",unsupported:"Not supported",unsafe:"Safety restriction"})[payload.status] || payload.status;
  $("identity").textContent = payload.request_id;
  $("answered-question").textContent = `${payload.question || ""} · Mode: ${payload.query_kind || "default"}`;
  const meanings = {verified:"Metric definitions were reviewed; this does not certify the user's intent.",partially_verified:"Some definitions were reviewed; additional question scope is not fully verified.",unverified_semantics:"Calculated from schema and column meanings, without reviewed business semantics."};
  $("verification").textContent = payload.verification ? `${payload.verification} · ${meanings[payload.verification] || ""}` : "No verification level was provided for this result.";
  $("interpretation").textContent = payload.interpretation || "No calculation interpretation was produced.";
  $("refusal").textContent = [payload.reason, payload.clarification].filter(Boolean).join("\n");
  list("assumptions", payload.assumptions);
  list("warnings", payload.warnings);
  const rows = payload.rows || [];
  $("rowmeta").textContent = payload.status === "answered" ? `Showing ${rows.length} rows; the tool reports ${payload.row_count} rows.${payload.rows_truncated ? " Results are truncated, not a complete result or ranking." : ""}` : "A refusal or execution failure is not a zero-count answer.";
  const columns = [...new Set(rows.flatMap(row => Object.keys(row)))];
  const head = document.createElement("tr");
  for (const column of columns) { const th = document.createElement("th"); th.textContent = column; head.append(th); }
  const body = rows.map(row => { const tr = document.createElement("tr"); for (const column of columns) { const td = document.createElement("td"); td.textContent = Object.hasOwn(row, column) ? text(row[column]) : "—"; tr.append(td); } return tr; });
  $("rows").replaceChildren(head, ...body);
  $("evidence").textContent = JSON.stringify(toolResult, null, 2);
}
function idle() { $("submit").disabled = false; $("stop").disabled = true; controller = null; for (const id of ["datasource", "question", "asof", "query-kind"]) $(id).disabled = false; }
$("stop").addEventListener("click", () => {
  generation++; controller?.abort(); idle(); $("progress").textContent = "Stopped. Remote model work may not stop immediately.";
});
$("query").addEventListener("submit", async e => {
  e.preventDefault(); if (controller) return;
  const current = ++generation; controller = new AbortController();
  $("submit").disabled = true; $("stop").disabled = false;
  for (const id of ["datasource", "question", "asof", "query-kind"]) $(id).disabled = true;
  $("result").hidden = true; toolResult = null; $("evidence").textContent = "";
  $("rows").replaceChildren(); $("progress").textContent = "Sending…";
  let terminal = false;
  try {
    const response = await fetch("/query", {method:"POST", headers:{"Content-Type":"application/json","X-Grepbit-Local":"1"}, signal:controller.signal,
      body:JSON.stringify({datasource_id:$("datasource").value,question:$("question").value,as_of:$("asof").value,query_kind:$("query-kind").value})});
    if (!response.ok) { const data = await response.json(); throw new Error(data.error || "request_failed"); }
    const reader = response.body.getReader(), decoder = new TextDecoder(); let buffer = "";
    while (true) {
      const {value, done} = await reader.read();
      if (current !== generation) return;
      buffer += decoder.decode(value, {stream:!done});
      let split;
      while ((split = buffer.indexOf("\n\n")) >= 0) {
        const block = buffer.slice(0, split); buffer = buffer.slice(split + 2);
        const kind = block.split("\n").find(line => line.startsWith("event: "))?.slice(7);
        const line = block.split("\n").find(line => line.startsWith("data: "));
        if (!line) continue;
        const data = JSON.parse(line.slice(6));
        if (terminal) throw new Error("unexpected_stream_event");
        if (kind === "progress") $("progress").textContent = data.state === "accepted" ? "Accepted. Query running…" : "Still running. Waiting for the tool result…";
        if (kind === "result") { terminal = true; render(data); $("progress").textContent = "Tool result received in full"; }
        if (kind === "error") { terminal = true; throw new Error(data.code); }
      }
      if (done) break;
    }
    if (!terminal) throw new Error("stream_interrupted");
  } catch (error) {
    if (current === generation) $("progress").textContent = `Not completed: ${error.message}`;
  } finally { if (current === generation) idle(); }
});
let examples = {};
let rowDatasources = [];
function selectDatasource() {
  $("query-kind").value = "default";
  $("rows-mode").disabled = !rowDatasources.includes($("datasource").value);
  const guide = Object.hasOwn(examples, $("datasource").value) ? examples[$("datasource").value] : null;
  $("asof").value = guide?.as_of || "";
  $("source-summary").textContent = guide?.summary || "No fixture guide is available. Enter an explicit reporting time.";
  $("source-limitations").textContent = guide?.limitations || "";
  $("example-questions").replaceChildren(...(guide?.questions || []).map(question => {
    const button = document.createElement("button"); button.type = "button"; button.textContent = question;
    button.addEventListener("click", () => { if (!controller) $("question").value = question; });
    return button;
  }));
}
$("datasource").addEventListener("change", selectDatasource);
async function readConfig(path) {
  const response = await fetch(path); if (!response.ok) throw new Error(); return response.json();
}
Promise.all([readConfig("/config"), readConfig("/examples.json")]).then(([config, guides]) => {
  examples = guides;
  rowDatasources = config.row_datasources || [];
  for (const id of config.datasources) { const option = document.createElement("option"); option.value = id; option.textContent = id; $("datasource").append(option); }
  $("datasource").value = config.datasources[0] || "";
  selectDatasource();
}).catch(() => { $("progress").textContent = "Could not load local configuration"; $("submit").disabled = true; });
