"use strict";
const $ = id => document.getElementById(id);
let controller = null;
let generation = 0;
let toolResult = null; // Page memory only; never regenerated by a narration model.
const text = value => value === null ? "NULL（無值）" : typeof value === "object" ? JSON.stringify(value) : String(value);
function list(id, values) {
  $(id).replaceChildren(...(values || []).map(value => {
    const li = document.createElement("li"); li.textContent = text(value); return li;
  }));
}
function render(payload) {
  toolResult = payload;
  $("result").hidden = false;
  $("status").textContent = ({answered:"查詢完成",failed:"執行失敗",clarify:"需要釐清",semantic_gap:"缺少業務定義",unsupported:"尚不支援",unsafe:"安全限制"})[payload.status] || payload.status;
  $("identity").textContent = payload.request_id;
  $("answered-question").textContent = payload.question || "";
  const meanings = {verified:"已審核指標定義；不代表已認證使用者意圖。",partially_verified:"部分定義已審核；問題新增的範圍未獲完整語意認證。",unverified_semantics:"依 schema／欄位意義計算，尚未經業務語意審核。"};
  $("verification").textContent = payload.verification ? `${payload.verification} · ${meanings[payload.verification] || ""}` : "此結果未提供驗證等級。";
  $("interpretation").textContent = payload.interpretation || "未產生計算口徑。";
  $("refusal").textContent = [payload.reason, payload.clarification].filter(Boolean).join("\n");
  list("assumptions", payload.assumptions);
  list("warnings", payload.warnings);
  const rows = payload.rows || [];
  $("rowmeta").textContent = payload.status === "answered" ? `顯示 ${rows.length} 列；工具回報 ${payload.row_count} 列${payload.rows_truncated ? "。結果已截斷，非完整結果／排名。" : "。"}` : "未將拒答或執行失敗當成零筆答案。";
  const columns = [...new Set(rows.flatMap(row => Object.keys(row)))];
  const head = document.createElement("tr");
  for (const column of columns) { const th = document.createElement("th"); th.textContent = column; head.append(th); }
  const body = rows.map(row => { const tr = document.createElement("tr"); for (const column of columns) { const td = document.createElement("td"); td.textContent = Object.hasOwn(row, column) ? text(row[column]) : "—"; tr.append(td); } return tr; });
  $("rows").replaceChildren(head, ...body);
  $("evidence").textContent = JSON.stringify(toolResult, null, 2);
}
function idle() { $("submit").disabled = false; $("stop").disabled = true; controller = null; for (const id of ["datasource", "question", "asof"]) $(id).disabled = false; }
$("stop").addEventListener("click", () => {
  generation++; controller?.abort(); idle(); $("progress").textContent = "已停止；遠端模型工作不保證立即終止。";
});
$("query").addEventListener("submit", async e => {
  e.preventDefault(); if (controller) return;
  const current = ++generation; controller = new AbortController();
  $("submit").disabled = true; $("stop").disabled = false;
  for (const id of ["datasource", "question", "asof"]) $(id).disabled = true;
  $("result").hidden = true; toolResult = null; $("evidence").textContent = "";
  $("rows").replaceChildren(); $("progress").textContent = "送出中…";
  let terminal = false;
  try {
    const response = await fetch("/query", {method:"POST", headers:{"Content-Type":"application/json","X-Grepbit-Local":"1"}, signal:controller.signal,
      body:JSON.stringify({datasource_id:$("datasource").value,question:$("question").value,as_of:$("asof").value})});
    if (!response.ok) { const data = await response.json(); throw new Error(data.error || "request_failed"); }
    const reader = response.body.getReader(), decoder = new TextDecoder(); let buffer = "";
    while (true) {
      const {value, done} = await reader.read();
      if (current !== generation) return;
      buffer += decoder.decode(value, {stream:!done});
      let split;
      while ((split = buffer.indexOf("\n\n")) >= 0) {
        const block = buffer.slice(0, split); buffer = buffer.slice(split + 2);
        const kind = block.split("\n").find(line => line.startsWith("event: "))?.slice(7);
        const line = block.split("\n").find(line => line.startsWith("data: "));
        if (!line) continue;
        const data = JSON.parse(line.slice(6));
        if (terminal) throw new Error("unexpected_stream_event");
        if (kind === "progress") $("progress").textContent = data.state === "accepted" ? "已接受，查詢執行中…" : "仍在執行，等待工具結果…";
        if (kind === "result") { terminal = true; render(data); $("progress").textContent = "工具結果已完整接收"; }
        if (kind === "error") { terminal = true; throw new Error(data.code); }
      }
      if (done) break;
    }
    if (!terminal) throw new Error("stream_interrupted");
  } catch (error) {
    if (current === generation) $("progress").textContent = `未完成：${error.message}`;
  } finally { if (current === generation) idle(); }
});
fetch("/config").then(response => { if (!response.ok) throw new Error(); return response.json(); }).then(config => {
  for (const id of config.datasources) { const option = document.createElement("option"); option.value = id; option.textContent = id; $("datasource").append(option); }
}).catch(() => { $("progress").textContent = "無法載入本機設定"; $("submit").disabled = true; });
