"""Owner-approved semantics: hand-computed values, not oracle agreement.

These expectations failed on the pre-implementation compiler and reference.
Default execution is offline. Setting GREPBIT_PERIOD_RULER_DSN_ENV to an
authorised DSN variable name adds PostgreSQL arms, with inline synthetic VALUES
in read-only transactions: no database tables are read or written. Expected
answers are never generated by a production time helper or another evaluator.
"""

from __future__ import annotations

import os
from datetime import date, datetime
from zoneinfo import ZoneInfo

import pytest
from t0_helpers import AS_OF, col

from evals.reference_eval import evaluate
from evals.synthetic import DuckInstance
from grepbit.adapters.sqlglot.plan_compiler import PlanCompiler
from grepbit.domain.plan import QueryPlan
from grepbit.domain.schema_model import ColumnKind, SchemaModel, SchemaTable


def _schema(kind, timezone):
    return SchemaModel(
        datasource_id="period_ruler",
        schema_name="public",
        business_timezone=timezone,
        tables=[
            SchemaTable(
                name="events",
                primary_key=["id"],
                columns=[
                    col("id", ColumnKind.NUMERIC, data_type="integer", nullable=False),
                    col("category", ColumnKind.TEXT),
                    col("occurred_at", kind),
                    col("amount", ColumnKind.NUMERIC),
                ],
            )
        ],
        foreign_keys=[],
    )


def _rows(points, kind=ColumnKind.TIMESTAMP, timezone="Asia/Taipei"):
    rows = []
    for i, (day, amount, category) in enumerate(points):
        moment = None
        if day is not None:
            moment = (
                date.fromisoformat(day)
                if kind == ColumnKind.DATE
                else datetime.fromisoformat(day).replace(tzinfo=ZoneInfo(timezone))
            )
        rows.append(
            {"id": i + 1, "occurred_at": moment, "amount": amount, "category": category}
        )
    return rows


def _growth(grain="month"):
    return {
        "base_table": "events",
        "measures": [
            {
                "aggregate": "sum",
                "column": {"table": "events", "column": "amount"},
                "alias": "total",
            }
        ],
        "time": {
            "column": {"table": "events", "column": "occurred_at"},
            "grain": grain,
        },
        "growth": [{"measure": "total"}],
    }


_ENGINES = ["compiled_sql", "reference"]
if os.environ.get("GREPBIT_PERIOD_RULER_DSN_ENV"):
    _ENGINES += ["postgres_UTC", "postgres_America/Los_Angeles"]


def _postgres_rows(compiled, rows, kind, session_zone):
    import psycopg
    from psycopg.rows import dict_row

    # Fixed synthetic relation only; do not rewrite arbitrary SQL or include
    # credential values in assertion messages, exception details or artifacts.
    sql = compiled.physical_sql
    assert sql.count("public.events") == 1
    parameters = {p.name: p.value for p in compiled.execution_parameters}
    tuples = []
    types = [
        "integer",
        "text",
        "date" if kind == ColumnKind.DATE else "timestamptz",
        "numeric",
    ]
    for i, row in enumerate(rows):
        fields = []
        for name, typ in zip(
            ["id", "category", "occurred_at", "amount"], types, strict=True
        ):
            key = f"fixture_{i}_{name}"
            parameters[key] = row[name]
            fields.append(f"%({key})s::{typ}")
        tuples.append(f"({', '.join(fields)})")
    relation = (
        f"(VALUES {', '.join(tuples)}) AS events (id, category, occurred_at, amount)"
    )
    sql = sql.replace("public.events", relation, 1)
    try:
        with psycopg.connect(
            os.environ[os.environ["GREPBIT_PERIOD_RULER_DSN_ENV"]],
            connect_timeout=5,
            row_factory=dict_row,
        ) as connection:
            connection.execute("BEGIN READ ONLY")
            assert (
                connection.execute("SELECT current_user AS role").fetchone()["role"]
                == "grepbit_ro"
            )
            connection.execute("SELECT set_config('statement_timeout', '5000', true)")
            connection.execute(
                "SELECT set_config('TimeZone', %s, true)", (session_zone,)
            )
            return connection.execute(sql, parameters).fetchall()
    except psycopg.Error as error:
        pytest.fail(
            f"postgres_ruler_error:{error.sqlstate or type(error).__name__}",
            pytrace=False,
        )


@pytest.fixture(params=_ENGINES)
def run_plan(request):
    def run(payload, points, *, kind=ColumnKind.TIMESTAMP, timezone="Asia/Taipei"):
        schema = _schema(kind, timezone)
        tables = {"events": _rows(points, kind, timezone)}
        plan = QueryPlan.model_validate(payload)
        compiled = PlanCompiler(schema).compile(plan, as_of=AS_OF)
        if request.param == "reference":
            rows = evaluate(plan, schema, None, AS_OF, tables)
        elif request.param.startswith("postgres_"):
            rows = _postgres_rows(
                compiled.compiled,
                tables["events"],
                kind,
                request.param.removeprefix("postgres_"),
            )
        else:
            instance = DuckInstance(schema, tables)
            try:
                names, values = instance.execute(compiled.compiled)
                rows = [dict(zip(names, row, strict=True)) for row in values]
            finally:
                instance.con.close()
        # Compare actual values by named columns; do not use differential's
        # comparator, and do not obtain expected periods from the time helpers.
        normalized = [
            {k: str(v)[:10] if k == "period_start" else v for k, v in row.items()}
            for row in rows
        ]
        return compiled, sorted(
            normalized,
            key=lambda row: (row.get("period_start", ""), row.get("category", "")),
        )

    return run


@pytest.mark.parametrize("kind", [ColumnKind.DATE, ColumnKind.TIMESTAMP])
@pytest.mark.parametrize(
    ("grain", "dates"),
    [
        ("day", ["2026-03-01", "2026-03-03", "2026-03-04"]),
        ("week", ["2026-03-02", "2026-03-16", "2026-03-23"]),
        ("month", ["2025-12-01", "2026-02-01", "2026-03-01"]),
        ("quarter", ["2025-10-01", "2026-04-01", "2026-07-01"]),
        ("year", ["2023-01-01", "2025-01-01", "2026-01-01"]),
    ],
)
def test_growth_requires_adjacent_calendar_periods_without_filling_rows(
    run_plan, kind, grain, dates
):
    points = [
        (d, amount, "A") for d, amount in zip(dates, [100, 120, 180], strict=True)
    ]
    _, actual = run_plan(_growth(grain), points, kind=kind)
    assert actual == [
        {"period_start": dates[0], "total": 100, "total_growth": None},
        {"period_start": dates[1], "total": 120, "total_growth": None},
        {"period_start": dates[2], "total": 180, "total_growth": 0.5},
    ]  # the gap is not 20%; no synthetic period is returned


def test_growth_adjacency_is_per_group(run_plan):
    payload = _growth()
    payload["dimensions"] = [{"table": "events", "column": "category"}]
    _, actual = run_plan(
        payload,
        [
            ("2026-01-01", 100, "A"),
            ("2026-03-01", 120, "A"),
            ("2026-02-01", 50, "B"),
            ("2026-03-01", 100, "B"),
        ],
    )
    assert actual == [
        {
            "period_start": "2026-01-01",
            "category": "A",
            "total": 100,
            "total_growth": None,
        },
        {
            "period_start": "2026-02-01",
            "category": "B",
            "total": 50,
            "total_growth": None,
        },
        {
            "period_start": "2026-03-01",
            "category": "A",
            "total": 120,
            "total_growth": None,
        },
        {
            "period_start": "2026-03-01",
            "category": "B",
            "total": 100,
            "total_growth": 1.0,
        },
    ]


def test_zero_denominator_and_null_values_do_not_become_zero_growth(run_plan):
    _, actual = run_plan(
        _growth(),
        [
            ("2026-01-01", 0, "A"),
            ("2026-02-01", 10, "A"),
            ("2026-03-01", None, "A"),
            ("2026-04-01", 20, "A"),
            ("2026-05-01", 30, "A"),
        ],
    )
    assert [r["total_growth"] for r in actual] == [None, None, None, None, 0.5]
    assert [r["total"] for r in actual] == [0, 10, None, 20, 30]


def test_adjacent_business_days_across_dst_remain_comparable(run_plan):
    _, actual = run_plan(
        _growth("day"),
        [
            ("2026-03-07", 100, "A"),
            ("2026-03-08", 200, "A"),
            ("2026-03-09", 300, "A"),
        ],
        timezone="America/New_York",
    )
    assert [r["period_start"] for r in actual] == [
        "2026-03-07",
        "2026-03-08",
        "2026-03-09",
    ]
    assert [r["total_growth"] for r in actual] == [None, 1.0, 0.5]


def test_null_time_rows_are_not_periods_but_remain_in_unperiodized_totals(run_plan):
    payload = _growth()
    payload.pop("growth")
    points = [("2026-01-01", 10, "A"), (None, 99, "A"), ("2026-03-01", 30, "A")]
    compiled, actual = run_plan(payload, points)
    assert actual == [
        {"period_start": "2026-01-01", "total": 10},
        {"period_start": "2026-03-01", "total": 30},
    ]
    assert any("are in no period" in a.text for a in compiled.assumptions)
    payload.pop("time")
    _, all_rows = run_plan(payload, points)
    assert all_rows == [{"total": 139}]


def test_a_population_with_only_null_time_has_no_period_rows(run_plan):
    _, actual = run_plan(_growth(), [(None, 99, "A")])
    assert actual == []


def test_share_threshold_selects_rows_without_shrinking_the_denominator(run_plan):
    payload = _growth()
    payload.pop("time")
    payload.pop("growth")
    payload["dimensions"] = [{"table": "events", "column": "category"}]
    payload["measures"].append(
        {**payload["measures"][0], "alias": "share", "share_of_total": True}
    )
    payload["having"] = [{"field": "total", "op": "gt", "value": 50}]
    compiled, actual = run_plan(
        payload, [("2026-01-01", 80, "A"), ("2026-01-01", 20, "B")]
    )
    assert actual == [{"category": "A", "total": 80, "share": 0.8}]
    assert any(
        h.startswith("[after share and growth]") for h in compiled.lineage.having
    )


def test_growth_threshold_hides_a_period_without_removing_its_comparison_value(
    run_plan,
):
    payload = _growth()
    payload["having"] = [{"field": "total", "op": "gt", "value": 50}]
    compiled, actual = run_plan(
        payload,
        [
            ("2026-01-01", 100, "A"),
            ("2026-02-01", 20, "A"),
            ("2026-03-01", 120, "A"),
        ],
    )
    assert actual == [
        {"period_start": "2026-01-01", "total": 100, "total_growth": None},
        {"period_start": "2026-03-01", "total": 120, "total_growth": 5.0},
    ]  # February exists but is hidden: it is not the missing-period case.
    assert any(
        h.startswith("[after share and growth]") for h in compiled.lineage.having
    )
