#!/usr/bin/env python3
"""Generate STATE.md from the registries and the run index (#87 step 4).

STATE.md is the handoff page: the current candidate, every registered panel with
its tier and latest result per route, the routes, the last runs and where the
open work lives. It is derived only from committed files, so it is
deterministic; a ruler keeps the committed page equal to the generated one.
Offline: no git, network, credentials or model.
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from tools import candidate_registry as registry, evaluate as runner, p3_assets as assets

STATE = ROOT / "STATE.md"
SOURCES = ("evals/candidates/index.json", "evals/panels/index.json", "evals/routes/index.json",
           "evals/runs/index.jsonl")
CLAIM_LABEL = {"development_observation": "dev", "observed_regression": "regression",
               "fresh_holdout_observation": "fresh"}


def _sources_digest() -> str:
    digest = hashlib.sha256()
    for name in SOURCES:
        path = ROOT / name
        digest.update(name.encode())
        digest.update(path.read_bytes() if path.exists() else b"")
    return digest.hexdigest()


def _input_count(entry: dict, runs: list[dict]) -> str:
    path = ROOT / entry["path"]
    if path.exists() and entry["allocation_policy"] is None:
        try:
            return str(len(assets.load_panel(path).cases))
        except assets.P3Error:
            pass
    counts = {run["inputs"] for run in runs if run["panel_id"] == entry["panel_id"]}
    return str(max(counts)) if counts else "?"


def render() -> str:
    index = registry.load_index()
    current = registry.current()
    panels = runner.load_panels()["panels"]
    routes = runner.load_routes()["routes"]
    runs = runner.load_runs()
    lines = ["# Project state", "",
             "Generated by `tools/state.py` from the committed registries and run index; "
             f"sources digest `{_sources_digest()[:16]}`. Regenerate with "
             "`.venv/bin/python tools/state.py --write` after any registry or index change.", "",
             "## Current candidate", "",
             f"- `{current['candidate_id']}` (semantic identity `{current['semantic_identity_sha256'][:16]}…`, "
             f"candidate digest `{current['candidate_sha256'][:16]}…`, behaviour digest "
             f"`{registry.behavior_identity(current)[:16]}…`), registered {current['registered_at'][:10]}; "
             f"{len(index['entries'])} registered candidate(s) in `evals/candidates/`.",
             f"- Note: {current['note']}", "",
             "## Panels and latest results per route", "",
             "| Panel | Tier | Inputs | Authoring | " + " | ".join(route["route_id"] for route in routes) + " |",
             "| --- | --- | --- | --- | " + " | ".join("---" for _ in routes) + " |"]
    for entry in panels:
        cells = []
        for route in routes:
            matching = [run for run in runs if run["panel_id"] == entry["panel_id"] and run["route_id"] == route["route_id"]
                        and run["candidate_id"] == current["candidate_id"] and run["tier"] == entry["tier"]]
            if not matching:
                claim = runner.derive_claim(entry["tier"], entry["panel_id"], route["route_id"], runs)
                cells.append("none (next: fresh)" if claim == "fresh_holdout_observation" else "none")
                continue
            last = matching[-1]
            cells.append(f"{last['correct']}/{last['inputs']}, {last['families_correct']}/{last['families']} fam "
                         f"({CLAIM_LABEL[last['claim']]}, {last['recorded_at'][:10]}, report `{last['report_sha256'][:8]}`"
                         + (", incomplete" if last["status"] != "complete" else "") + ")")
        lines.append(f"| `{entry['panel_id']}` | {entry['tier']} | {_input_count(entry, runs)} | {entry['authoring']} | "
                     + " | ".join(cells) + " |")
    lines += ["", "Cells show the last recorded run of the current candidate on that panel and route (file order "
              "of the run index). Claims: dev = development observation (agent-authored, never fresh); regression = "
              "observed regression on exposed data; fresh = the one fresh holdout observation per panel and route, "
              "after which that panel is regression data for that route. Nothing here is promotion.", "",
              "## Routes", "", "| Route | Provider | Model | Region | Call timeout | Transport |", "| --- | --- | --- | --- | --- | --- |"]
    for route in routes:
        lines.append(f"| `{route['route_id']}` | {route['provider']} | `{route['model']}` | {route['region'] or '-'} | "
                     f"{route['call_timeout_seconds']:.0f} s | {route['transport_security']} |")
    lines += ["", "## Last runs", "", "| Recorded | Run | Claim | Result | Status |", "| --- | --- | --- | --- | --- |"]
    for run in runs[-10:][::-1]:
        lines.append(f"| {run['recorded_at'][:10]} | `{run['run_id']}` | {CLAIM_LABEL[run['claim']]} | "
                     f"{run['correct']}/{run['inputs']}, {run['families_correct']}/{run['families']} fam | {run['status']} |")
    lines += ["", "## Where the work lives", "",
              "- Decisions: GitHub issues labelled `decision` (ADR form). Defects: `defect`. Evidence: `evidence` "
              "and the run index `evals/runs/index.jsonl`.",
              "- Process: `AGENTS.md`. Evaluation: `docs/evaluation-runner.md`, `docs/candidate-registry.md`, "
              "`docs/coverage-matrix.md`. Semantic contract: `docs/p3-evaluation-contract.md`.",
              "- Local archives under `.artifacts/` are not in git; the registries and `evals/runs/index.jsonl` "
              "pin them by digest (report digest prefixes are shown in the cells above).", ""]
    return "\n".join(lines)


def main(argv=None) -> int:
    args = list(sys.argv[1:] if argv is None else argv)
    text = render()
    if args == ["--write"]:
        STATE.write_text(text, encoding="utf-8")
        print(f"wrote {STATE.relative_to(ROOT)}")
        return 0
    if args == ["--check"]:
        if STATE.exists() and STATE.read_text(encoding="utf-8") == text:
            print("STATE.md is current")
            return 0
        print("STATE.md is stale; run tools/state.py --write", file=sys.stderr)
        return 1
    if args:
        print("usage: tools/state.py [--write|--check]", file=sys.stderr)
        return 2
    print(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
